##########################################################################
# Routines containing templates to write CHARMM input files

# Routine to write pure liquid CHARMM input file for vaporization enthalpy and density
def write_dens_inp(ctx,dens_inp_name,top,scaled_par,pureliq,lpun,T):

    charmmContent = """* CHARMM input file for 
* Pure Liquid simulation with MTPs
* Generated by fitting wizard
*

bomlev 0
prnlev 2 node 0

set temp {T}

! read parameters and coordinates
read rtf card name "$CHMDIR/{top}"
read param card name "$CHMDIR/{scaled_par}"

OPEN UNIT 10 CARD READ NAME "$CHMDIR/{pureliq}"

READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

CRYSTAL DEFI CUBIC 28. 28. 28. 90. 90. 90.
CRYSTAL BUILD nope 0
image byres xcen 0.0 ycen 0.0 zcen 0.0 sele all end

! Non bonded parameters
NBONDS ATOM EWALD PMEWALD KAPPA 0.43  -
        FFTX 32 FFTY 32 FFTZ 32 ORDER 4 -
        CUTNB 14.0  CTOFNB 12.0 CTONNB 10.0 -
        LRC VDW VSWITCH -
        INBFRQ -1 IMGFRQ -1

SHAKE BONH PARA SELE ALL END

OPEN UNIT 40 CARD READ NAME "$CHMDIR/{lpun}"
MTPL MTPUNIT 40 ron2 10 roff2 12 ron3 9 roff3 11 -
        ron4 8 roff4 10 ron5 7 roff5 9
CLOSE UNIT 40

scalar mass stat
calc pmass = int ( ?stot  /  50.0 )
calc tmass = @pmass * 10

mini sd nstep 1000

mini abnr nstep 100

set tmin 50
dyna leap verlet start -                    ! use leap-frog verlet integrator
   timestep 0.001 nstep 40000 nprint 1000 - ! run 10K steps @ 1 fs time-steps
   firstt @tmin finalt @temp tbath @temp -      ! heat from @tmin K to @temp K (200 K)
   ihtfrq 1000 teminc 5 ieqfrq 0 -          ! heat the system 5K every 2500 steps
   iasors 1 iasvel 1 iscvel 0 ichecw 0 -    ! assign velocities via a Gaussian
   ntrfrq 500 -                             ! stop rotation and translation
   iseed  11033 -                           ! pick a random seed for the
   echeck 100.0                             ! If energy changes more than 100

dyna leap cpt nstep 40000 timestep 0.001 -
  nprint 100 nsavc 100 iuncrd 50 ntrfrq 200 -
  iprfrq 50000 inbfrq -1 imgfrq 50 ihtfrq 0 -
  ieqfrq 0 -
  pint pconst pref 1 pgamma 5 pmass @pmass -
  hoover reft @temp tmass @tmass firstt @temp

dyna leap nstep 40000 timestep 0.001 -
  nprint 100 nsavc 100 iuncrd 50 ntrfrq 200 -
  iprfrq 40000 inbfrq -1 imgfrq 50 ihtfrq 0 -
  ieqfrq 0 -
  cpt pint pconst pref 1 pgamma 0 pmass @pmass -
  hoover reft @temp tmass @tmass

STOP
""".format(T=T, inp_dir=ctx.input_dir.name, top=top, pureliq=pureliq, lpun=lpun, scaled_par=scaled_par)

    with ctx.input_dir.open_file(dens_inp_name, "w") as dens_liq_file:
       dens_liq_file.write(charmmContent)
    dens_liq_file.close()

    return dens_liq_file

##########################################################################

# Routine to write gas-phase CHARMM input for solute molecule for vaporization enthalpy
def write_gas_inp(ctx,dens_inp_name,top,scaled_par,slu,lpun):

   charmmContent="""* CHARMM input file for 
* Gas Phase simulation with MTPs
* Generated by fitting wizard
*

bomlev 0
prnlev 2 node 0 

! read parameters and coordinates
read rtf card name -
        "$CHMDIR/{top}"
read param card name -
        "$CHMDIR/{scaled_par}"

OPEN UNIT 10 CARD READ NAME -
        "$CHMDIR/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

! Non bonded parameters
NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
        VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

SHAKE BONH PARA SELE ALL END

OPEN UNIT 40 CARD READ NAME "$CHMDIR/{lpun}"
MTPL MTPUNIT 40
CLOSE UNIT 40

mini sd nstep 1000

mini abnr nstep 100

STOP
""".format(top=top, slu=slu, lpun=lpun, scaled_par=scaled_par)

   with ctx.input_dir.open_file(dens_inp_name, "w") as dens_gas_file:
       dens_gas_file.write(charmmContent)
   dens_gas_file.close()

   return dens_gas_file

##########################################################################

# Routine to write vdw input files for gas-phase TI calculations
def write_ti_vdw_gas_inp(top,par,slu,lstart,lstop,pstart,nstep,T):
   
    charmmContent="""* TI calculation for gas-phase vdw contribution to solvation
* free energy (generated by fitting wizard)
*

PRNLEV 2 NODE 0
BOMLEV 0

! use an environment variable in case path is > 80 characters:
SET PATH $CHMDIR 

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

FAST OFF  ! important, otherwise scalar RSCA has no effect!!
SCALAR CHARGE SET 0. SELE SEGI SOLU END
PERT SELE SEGI SOLU END
SCALAR RSCA SET 0. SELE SEGI SOLU END
SCALAR FBETA SET 5. SELE ALL END

NBONDS ATOM - ! EWALD PMEWALD KAPPA 0.32  -
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0  -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

DYNA LEAP STRT NSTEP {nstep} TIMESTEP 0.001 -
  NTRFRQ 100 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  LSTART {lstart} LAMBDA {lmid} LSTOP {lstop} PSTART  {pstart} -
  PSTOP {nstep} PSLOW LINCR {lincr} -
  PSSP TBATH {temp} RBUF 0. ILBFRQ 10 FIRSTT 240. -
  NPRINT 1000 NSAVC -1 -

STOP

""".format(par=par, top=top, slu=slu, nstep=nstep, lstart="%.6f"%lstart, lstop="%.6f"%lstop, 
           lmid="%.6f"%(lstart+(lstop-lstart)/2.0), pstart=pstart, temp=T, lincr=lstop-lstart)
    
    return charmmContent

##########################################################################

# Routine to write vdw input files for solvated-phase TI calculations
def write_ti_vdw_solv_inp(top,par,slu,slv,res,lstart,lstop,pstart,nstep,T):

    charmmContent="""* TI calculation for solution-phase VDW contribution to solvation
* free energy (generated by fitting wizard)
*

PRNLEV 2 NODE 0

SET PATH $CHMDIR

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

OPEN UNIT 10 READ CARD NAME "@PATH/{slv}"
READ SEQUENCE PDB UNIT 10
GENERATE WAT NOANgle NODIhedral
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

BOMLEV 0

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

FAST OFF ! so that scalar RSCA has some effect!

SCALAR CHARGE SET 0. SELE SEGI SOLU END
PERT SELE SEGI SOLU END
SCALAR RSCA SET 0. SELE SEGI SOLU END

SHAKE FAST WATER SELECT SEGI WAT END
COOR STAT
CALC BOXX = (?XMAX - ?XMIN -1.0)
CRYSTAL DEFI CUBIC @BOXX @BOXX @BOXX 90. 90. 90.
CRYSTAL BUILD nope 0
IMAGE BYRES XCEN 0.0 YCEN 0.0 ZCEN 0.0 SELE ALL END
NBONDS ATOM - ! EWALD PMEWALD KAPPA 0.32  -
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0 CUTIM 14.0 -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

!constrain molecule to center of box
cons hmcm force 1.0 refx 0.0 refy 0.0 refz 0.0 -
   select segid SOLU END

!!setting PMASS to zero means it will be NVT, but will still report the
!! pressure
!!see https://www.charmmtutorial.org/index.php/MD

open read  unit 32 card name "@PATH/{res}"
read coor dynr curr unit 32
bomlev  0


DYNA LEAP STRT NSTEP {nstep} TIMESTEP 0.001 -
iunread 32 iunwri -1 iunvel -1 kunit -1 -
  NTRFRQ 100 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  LSTART {lstart} LAMBDA {lmid} LSTOP {lstop} PSTART  {pstart} -  
  PSTOP {nstep} PSLOW LINCR {lincr} -
  PSSP IHTFRQ 0 IEQFRQ 0 -
  TSTRUCT {temp} FINALT {temp} FIRSTT {temp} -
  CPT PCONst PREF 1.0 PGAMMA 20.0 PMASs 0 -
  TBATH {temp} -
  NPRINT 1000 NSAVC -1 -

STOP

""".format(top=top, par=par, slu=slu, slv=slv, res=res, nstep=nstep, lstart="%.6f"%lstart,
           lstop="%.6f"%lstop, lmid="%.6f"%(lstart+(lstop-lstart)/2.0), pstart=pstart, temp=T,
           lincr=lstart-lstop)

    return charmmContent

##########################################################################

# Routine to write electrostatic input files for gas-phase TI calculations
def write_ti_elec_gas_inp(top,par,slu,lpun,lstart,lstop,equil,nstep,T):

    charmmContent="""* TI calculation for gas-phase electrostatic contribution to
* solvation free energy, scaled dynamics step (generated by fitting wizard)
*

PRNLEV 2 NODE 0

SET PATH $CHMDIR

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

BOMLEV 0

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

SCALAR CHARGE SET 0. SELE SEGI SOLU END
SCALAR FBETA SET 5. SELE ALL END

NBONDS ATOM - ! EWALD PMEWALD KAPPA 0.32  -
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0 -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

OPEN UNIT 40 CARD READ NAME "@PATH/{lpun}"
MTPL MTPUNIT 40 PREF {lmbd} !PREF scales only the multipoles and not the charges
CLOSE UNIT 40
SCALAR CHARGE MULT {lmbd} SELE SEGI SOLU END !does the charge scaling

! Equilibration

OPEN UNIT 31 WRITe CARD NAME equil.res             !Restart file

DYNA LEAP STRT NSTEP {equil} TIMESTEP 0.001 -
  NTRFRQ 100 IUNWRI 31 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  TBATH {temp} RBUF 0. ILBFRQ 10 FIRSTT 240. -
  NPRINT 100

! Dynamics

OPEN WRITE UNIT 50 NAME lambda_{lmbd}.gas.mtpl.trj
OPEN UNIT 11 READ CARD NAME equil.res

DYNA LEAP RESTart NSTEP {nstep} TIMESTEP 0.001 -
  NTRFRQ 100 IUNREA 11 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  TBATH {temp} RBUF 0. ILBFRQ 10 FIRSTT 240. -
  NPRINT 100 NSAVC 100 IUNCRD 50

STOP

""".format(top=top, par=par, slu=slu, lmbd="%.6f"%(lstart+(lstop-lstart)/2.0), lpun=lpun, equil=equil, nstep=nstep-equil, temp=T)

    return charmmContent


##########################################################################

# Routine to write electrostatic input files for gas-phase TI calculations
def write_ti_elec_gas_trajread_inp(top,par,slu,lpun,lstart,lstop,T):

    charmmContent="""* TI calculation for gas-phase electrostatic contribution to
* solvation free energy, trajectory read, unscaled electrostatic step
* (generated by fitting wizard)
*

PRNLEV 2 NODE 0

SET PATH $CHMDIR

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

BOMLEV 0

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

SCALAR CHARGE SET 0. SELE SEGI SOLU END
SCALAR FBETA SET 5. SELE ALL END

NBONDS ATOM - 
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0 -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

OPEN UNIT 40 CARD READ NAME "@PATH/{lpun}"
MTPL MTPUNIT 40
CLOSE UNIT 40

OPEN READ UNIT 50 NAME lambda_{lmbd}.gas.mtpl.trj

CONS FIX SELE .NOT. SEGI SOLU END
TRAJECTORY FIRSTUNIT 50 NUNIT 6 SKIP 1
SET NTRAJ 0
STREAM "@PATH/loop.str"
CLOSE UNIT 50

STOP

""".format(top=top, par=par, slu=slu, lmbd="%.6f"%(lstart+(lstop-lstart)/2.0), lpun=lpun, temp=T)

    return charmmContent


##########################################################################

# Routine to write electrostatic input files for gas-phase TI calculations
def write_ti_elec_solv_inp(top,par,slu,slv,res,lpun,lstart,lstop,equil,nstep,T):

    charmmContent="""* TI calculation for solution-phase electrostatic contribution to
* solvation free energy, scaled dynamics step (generated by fitting
* wizard)
*

PRNLEV 2 NODE 0

SET PATH $CHMDIR

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

OPEN UNIT 10 READ CARD NAME "@PATH/{slv}"
READ SEQUENCE PDB UNIT 10
GENERATE WAT NOANgle NODIhedral
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

BOMLEV 0

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

SCALAR CHARGE SET 0. SELE SEGI SOLU END


SHAKE FAST WATER SELECT SEGI WAT END
COOR STAT
CALC BOXX = (?XMAX - ?XMIN -1.0)
CRYSTAL DEFI CUBIC @BOXX @BOXX @BOXX 90. 90. 90.
CRYSTAL BUILD nope 0
IMAGE BYRES XCEN 0.0 YCEN 0.0 ZCEN 0.0 SELE ALL END
NBONDS ATOM - ! EWALD PMEWALD KAPPA 0.32  -
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0 CUTIM 14.0 -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

!constrain molecule to center of box
cons hmcm force 1.0 refx 0.0 refy 0.0 refz 0.0 -
   select segid SOLU END

OPEN UNIT 40 CARD READ NAME "@PATH/{lpun}"
MTPL MTPUNIT 40  PREF {lmbd} !PREF scales the multipoles only, not the charges
CLOSE UNIT 40
SCALAR CHARGE MULT {lmbd} SELE SEGI SOLU END !scales the charges

! Equilibration

  open read  unit 32 card name "@PATH/{res}"
  read coor dynr curr unit 32
  bomlev  0

OPEN UNIT 31 WRITe CARD NAME equil.res             !Restart file

DYNA LEAP STRT NSTEP {equil} TIMESTEP 0.001 -
  NTRFRQ 100 IUNWRI 31 IUNREA 32 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  IHTFRQ 0 IEQFRQ 0 -
  TSTRUCT {temp} FINALT {temp} FIRSTT {temp} -
  CPT PCONst PREF 1.0 PGAMMA 20.0 PMASs 0 -
  TBATH {temp} -
  NPRINT 1000

! Dynamics

OPEN WRITE UNIT 50 NAME lambda_{lmbd}.solv.mtpl.trj
OPEN UNIT 11 READ CARD NAME equil.res

! estimate Pmass from SYSmass (total system mass)
! [there could be problems with exreme values, such as  Pmass << SYSmass or
! Pmass >> SYSmass
scalar mass stat
calc Pmass = int ( ?stot  /  50.0 )

DYNA LEAP RESTART NSTEP {nstep} TIMESTEP 0.001 -
  NTRFRQ 100 IUNREA 11 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  IHTFRQ 0 IEQFRQ 0 -
  TSTRUCT {temp} FINALT {temp} FIRSTT {temp} -
  CPT PCONst PREF 1.0 PGAMMA 20.0 PMASs 0 -
  TBATH {temp} -
  NPRINT 100 NSAVC 100 IUNCRD 50

STOP

""".format(top=top, par=par, slu=slu, slv=slv, res=res, lmbd="%.6f"%(lstart+(lstop-lstart)/2.0), lpun=lpun, equil=equil, nstep=nstep-equil, temp=T)

    return charmmContent

##########################################################################

# Routine to write electrostatic input files for gas-phase TI calculations
def write_ti_elec_solv_trajread_inp(top,par,slu,slv,lpun,lstart,lstop,T):

    charmmContent="""* TI calculation for solution-phase electrostatic contribution to
* solvation free energy, trajectory read with unscaled electrostatics
* step (generated by fitting wizard)
*

PRNLEV 2 NODE 0

SET PATH $CHMDIR

READ RTF CARD        NAME -
 "@PATH/{top}"

READ PARAM CARD        NAME -
 "@PATH/{par}"

OPEN UNIT 10 READ CARD NAME "@PATH/{slu}"
READ SEQUENCE PDB UNIT 10
GENERATE SOLU
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

OPEN UNIT 10 READ CARD NAME "@PATH/{slv}"
READ SEQUENCE PDB UNIT 10
GENERATE WAT NOANgle NODIhedral
REWIND UNIT 10
READ COOR PDB UNIT 10
CLOSE UNIT 10

BOMLEV 0

NBONDS NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFT VATOM VDISTANCE -
  VSWITCH CUTNB 99.0 CTOFNB 98.0 CTONNB 97. E14FAC 1.0

SCALAR CHARGE SET 0. SELE SEGI SOLU END

SHAKE FAST WATER SELECT SEGI WAT END
COOR STAT
CALC BOXX = (?XMAX - ?XMIN -1.0)
CRYSTAL DEFI CUBIC @BOXX @BOXX @BOXX 90. 90. 90.
CRYSTAL BUILD nope 0
IMAGE BYRES XCEN 0.0 YCEN 0.0 ZCEN 0.0 SELE ALL END
NBONDS ATOM - ! EWALD PMEWALD KAPPA 0.32  -
  CUTNB 14.0  CTOFNB 12.0 CTONnb 10.0 CUTIM 14.0 -
  atom vatom vdistance -
  VSWITCH SHIFT CDIE eps 1.0  e14fac 1.0  wmin 1.5

!constrain molecule to center of box
cons hmcm force 1.0 refx 0.0 refy 0.0 refz 0.0 -
   select segid SOLU END

OPEN UNIT 40 CARD READ NAME "@PATH/{lpun}"
MTPL MTPUNIT 40
CLOSE UNIT 40


OPEN READ UNIT 50 NAME lambda_{lmbd}.solv.mtpl.trj

CONS FIX SELE .NOT. SEGI SOLU END
TRAJECTORY FIRSTUNIT 50 NUNIT 6 SKIP 1
SET NTRAJ 0
STREAM "@PATH/loop.str"
CLOSE UNIT 50

STOP

""".format(top=top, par=par, slu=slu, slv=slv, lmbd="%.6f"%(lstart+(lstop-lstart)/2.0), lpun=lpun, temp=T)

    return charmmContent


