#!/bin/bash

# Generate cubic solute+water simulation box out of one molecule with top and
# pdb files.  Provides a box of ~500 molecules.
#
# Tristan BEREAU 12.06.2012

[ -z $3 ] && echo "missing arguments: mol.top mol.pdb mol.par" && exit 1 

top=$1
pdb=$2
par=$3
base=`basename $pdb .pdb`

for exe in vmd charmm; do
    type $exe >/dev/null 2>&1 || \
        { 
            echo >&2 "I require $exe but it's not installed.  Aborting."
            exit 1; 
        }
done

cat > vmd.tmp.tcl <<EOF
mol load pdb $base.pdb

autopsf -mol 0 -top $top
EOF

vmd < vmd.tmp.tcl > vmd.tmp.out || \
    { 
        echo "Error from VMD (vmd.tmp.out)" && exit 1
    }

[ ! -f ${base}_autopsf.psf ] && echo "VMD did not complete. Exiting" && exit 1

cat > vmd.tmp.tcl <<EOF
solvate ${base}_autopsf.psf ${base}_autopsf.pdb -o ${base}.slv -minmax {{-13 -13 -13} {13 13 13}}
mol load psf ${base}.slv.psf pdb ${base}.slv.pdb
set water [atomselect top "resname TIP3"]
set residueshifted [\$water get residue]
for {set i 0} {\$i < [llength \$residueshifted]} {incr i} {
    lset residueshifted \$i [expr [lindex \$residueshifted \$i]+1]
}
\$water set resid \$residueshifted
\$water writepdb water.pdb
EOF

vmd < vmd.tmp.tcl > vmd.tmp.out || \
    { 
        echo "Error from VMD (vmd.tmp.out)" && exit 1
    }

numwat=`cat water.pdb | wc -l`
[ "$numwat" -lt 100 ] && \
    echo "Error: Too few water molecules in water.pdb" && exit 1

# Generate CHARMM-compatible PSF, PDB, and CRD
cat > prep.inp <<EOF
* Read DCD file and calculate electrostatic energy.
*

bomlev 0
prnlev 2

set  mol      ${base}
envi mol      @mol
set  system   "pc"
set  pdb      "${base}.slv.pdb"
envi pdb      @pdb

!-- read parameters and coordinates
read rtf   card  name $top
read param card  name $par

open unit 10 read card name $pdb
read sequence pdb unit 10
generate LIG
rewind unit 10 
read coor pdb unit 10
close unit 10

open unit 10 read card name water.pdb
read sequence pdb unit 10
GENERATE WAT NOANgle NODIhedral
rewind unit 10
read coor pdb unit 10
close unit 10

minimize sd nstep 1000 mprint 100

open unit 11 card write name @mol.min.psf
write psf card unit 11
close unit 11

open unit 11 write card name @mol.min.crd
write coor card unit 11
close unit 11

open unit 11 write card name @mol.min.pdb
write coor pdb unit 11
close unit 11

STOP

EOF

echo "Running CHARMM to generate initial PSF and PDB..."
charmm < prep.inp > prep.out

tail -n 40 prep.out | \
    grep " NORMAL TERMINATION" >/dev/null 2>&1 || \
    { 
        echo "Error in CHARMM output prep.out" && exit 1 
    }

# Equilibrate
cat > equi.inp <<EOF
* Read DCD file and calculate electrostatic energy.
*

bomlev 0
prnlev 2

set  mol      ${base}
envi mol      @mol
set  system   "pc"
set  pdb      "${base}.slv.pdb"
envi pdb      @pdb

!-- read parameters and coordinates
read rtf   card  name $top
read param card  name $par
read psf  card name @mol.min.psf
read coor card name @mol.min.crd

ENERGY NBXMOD 5 ATOM CDIEL EPS 1.0 SHIFt VATOM VDISTANCE -
  VSWItch CUTNb 12.0 CTOFnb 11. CTONnb 10. E14Fac 1.0 

FAST OFF

SHAKE FAST WATER SELECT SEGI WAT END
COOR STAT
CALC BOXX = ?XMAX - ?XMIN
CALC BOXY = ?YMAX - ?YMIN
CALC BOXZ = ?ZMAX - ?ZMIN
CALC BAVE = (@BOXX + @BOXY + @BOXZ)/3.
CALC DEVX = abs( @BAVE - @BOXX )
CALC DEVY = abs( @BAVE - @BOXY )
CALC DEVZ = abs( @BAVE - @BOXZ )

if @DEVX .gt. 1.0 THEN STOP
if @DEVY .gt. 1.0 THEN STOP
if @DEVZ .gt. 1.0 THEN STOP

CRYSTAL DEFI CUBIC @BOXX @BOXX @BOXX 90. 90. 90. 
CRYSTAL BUILD nope 0
IMAGE BYRES XCEN 0.0 YCEN 0.0 ZCEN 0.0 SELE ALL END

NBONDS ATOM EWALD PMEWALD KAPPA 0.32  -
  FFTX 32 FFTY 32 FFTZ 32 ORDER 6 -
  CUTNB 12.0  CTOFNB 11.0 CTONnb 10.0

CONS HMCM FORCE 5.0 WEIGH REFX 0. REFY 0. REFZ 0. -
  SELECT SEGI LIG END

mini sd nstep 100

DYNA LEAP STRT NSTEP 1000 TIMESTEP 0.001 -
  NTRFRQ 100 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 250 -
  TCONST TCOUPL 1.0 TREFE 298.0 -
  NPRINT 100 NSAVC -1 -

DYNA LEAP STRT NSTEP 5000 TIMESTEP 0.001 -
  NTRFRQ 100 -
  IPRFRQ 0 INBFRQ -1 IMGFRQ 50 -
  IHTFRQ 0 IEQFRQ 0 TSTRUCT 298.0 FINALT 298.0 -
  FIRSTT 298.0 -
  CPT PCONst PREF 1.0 PGAMMA 20.0 PMASs 500 HOOVER -
  REFT 298.9 TMASS 4000.0 -
  NPRINT 100 NSAVC -1

open unit 11 write card name @mol.equi.pdb
write coor pdb unit 11
close unit 11

STOP
EOF

echo "Running CHARMM equilibration simulation..."
charmm < equi.inp > equi.out

tail -n 40 equi.out | \
    grep " NORMAL TERMINATION" >/dev/null 2>&1 || \
    { 
        echo "Error in CHARMM output equi.out" && exit 1 
    }

cat > vmd.tmp.tcl <<EOF
mol load psf ${base}.min.psf pdb ${base}.equi.pdb
set solute [atomselect top "segname LIG"]
set water [atomselect top "resname TIP3"]
\$solute writepdb solute.pdb
\$water writepdb solvent.pdb
EOF

vmd < vmd.tmp.tcl > vmd.tmp.out || \
    {
        echo "Error in VMD (vmd.tmp.out)" && exit 1
    }
echo "Solute stored in solute.pdb"
echo "Solvent stored in solvent.pdb"
