/*
 * Fitting service API
 * Provides operations for fitting algorithms
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AlgorithmList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T10:04:30.475Z")
public class AlgorithmList {
  @SerializedName("algorithms")
  private List<String> algorithms = new ArrayList<String>();

  public AlgorithmList algorithms(List<String> algorithms) {
    this.algorithms = algorithms;
    return this;
  }

  public AlgorithmList addAlgorithmsItem(String algorithmsItem) {
    this.algorithms.add(algorithmsItem);
    return this;
  }

   /**
   * List of registered algorithms
   * @return algorithms
  **/
  @ApiModelProperty(example = "[\"dummy_algorithm\"]", required = true, value = "List of registered algorithms")
  public List<String> getAlgorithms() {
    return algorithms;
  }

  public void setAlgorithms(List<String> algorithms) {
    this.algorithms = algorithms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmList algorithmList = (AlgorithmList) o;
    return Objects.equals(this.algorithms, algorithmList.algorithms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmList {\n");
    
    sb.append("    algorithms: ").append(toIndentedString(algorithms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

