/*
 * Fitting service API
 * Provides operations for fitting algorithms
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CalculationStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CalculationStatusList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-06T13:27:24.634Z")
public class CalculationStatusList {
  @SerializedName("calculations")
  private List<CalculationStatus> calculations = new ArrayList<CalculationStatus>();

  public CalculationStatusList calculations(List<CalculationStatus> calculations) {
    this.calculations = calculations;
    return this;
  }

  public CalculationStatusList addCalculationsItem(CalculationStatus calculationsItem) {
    this.calculations.add(calculationsItem);
    return this;
  }

   /**
   * Parameter for the fitting algorithm
   * @return calculations
  **/
  @ApiModelProperty(example = "[{\"id\":\"2018-04-05_13-42-43-207763_Nwfz0\",\"status\":{\"last_run\":\"2018-04-05_13-42-43-284265_SxcVY\",\"status\":\"Finished\",\"message\":\"\",\"calculation_parameters\":{\"parameters\":{\"calc_param1\":\"value1\",\"calc_param2\":\"value2\"}},\"run_parameters\":{\"algorithm\":\"dummy_algorithm\",\"parameters\":{\"calc_param1\":\"value1\",\"calc_param2\":\"value2\",\"run_param1\":\"value1\",\"run_param2\":\"value2\"}},\"input_files\":[\"somefile.json\"]}},{\"id\":\"2018-04-06_07-40-38-478641_a6XFG\",\"status\":{\"last_run\":\"2018-04-06_07-40-38-579644_-4bl6\",\"status\":\"Finished\",\"message\":\"\",\"calculation_parameters\":{\"parameters\":{\"calc_param1\":\"value1\",\"calc_param2\":\"value2\"}},\"run_parameters\":{\"algorithm\":\"dummy_algorithm\",\"parameters\":{\"calc_param1\":\"value1\",\"calc_param2\":\"value2\",\"run_param1\":\"value1\",\"run_param2\":\"value2\"}},\"input_files\":[\"somefile.json\"]}}]", required = true, value = "Parameter for the fitting algorithm")
  public List<CalculationStatus> getCalculations() {
    return calculations;
  }

  public void setCalculations(List<CalculationStatus> calculations) {
    this.calculations = calculations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculationStatusList calculationStatusList = (CalculationStatusList) o;
    return Objects.equals(this.calculations, calculationStatusList.calculations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calculations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculationStatusList {\n");
    
    sb.append("    calculations: ").append(toIndentedString(calculations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

