/*
 * Fitting service API
 * Provides operations for fitting algorithms
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * JobIdList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-06T13:27:24.634Z")
public class JobIdList {
  @SerializedName("jobs")
  private List<String> jobs = new ArrayList<String>();

  public JobIdList jobs(List<String> jobs) {
    this.jobs = jobs;
    return this;
  }

  public JobIdList addJobsItem(String jobsItem) {
    this.jobs.add(jobsItem);
    return this;
  }

   /**
   * List of calculation ids
   * @return jobs
  **/
  @ApiModelProperty(example = "[\"OEW1L\",\"ZKNDn\",\"UJP-n\",\"dsma9\",\"97S8j\",\"DtXXg\",\"H00g0\",\"023iV\",\"dMZ11\",\"Sykfq\",\"pUZLN\",\"Nwfz0\",\"a6XFG\"]", required = true, value = "List of calculation ids")
  public List<String> getJobs() {
    return jobs;
  }

  public void setJobs(List<String> jobs) {
    this.jobs = jobs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobIdList jobIdList = (JobIdList) o;
    return Objects.equals(this.jobs, jobIdList.jobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobIdList {\n");
    
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

