/*
 * Fitting service API
 * Provides operations for fitting algorithms
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Run
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-13T10:04:30.475Z")
public class Run {
  @SerializedName("algorithm")
  private String algorithm = null;

  @SerializedName("parameters")
  private String parameters = null;

  public Run algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Possible values: LJFit, MTPFit
   * @return algorithm
  **/
  @ApiModelProperty(example = "dummy_algorithm", required = true, value = "Possible values: LJFit, MTPFit")
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }

  public Run parameters(String parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Parameter for the fitting algorithm
   * @return parameters
  **/
  @ApiModelProperty(example = "{\"x\":1234, \"y\": 5678}", required = true, value = "Parameter for the fitting algorithm")
  public String getParameters() {
    return parameters;
  }

  public void setParameters(String parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Run run = (Run) o;
    return Objects.equals(this.algorithm, run.algorithm) &&
        Objects.equals(this.parameters, run.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Run {\n");
    
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

